#services:
#  mysql:
#    image: mysql:8.0
#    container_name: deskit-mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql1234
#      MYSQL_DATABASE: testdb
#      TZ: Asia/Seoul
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_0900_ai_ci
#    volumes:
#      - deskit_mysql_data:/var/lib/mysql
#volumes:
#  deskit_mysql_data:
